# Generated by Django 5.2.15 on 2026-06-21 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_overview_alcohol_use_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('boolean', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('rating', 'Rating Scale')], default='boolean', max_length=20)),
                ('is_criteria', models.BooleanField(default=False)),
                ('criteria_number', models.CharField(blank=True, max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('has_jump_logic', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewmodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.patient')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interview.interviewmodule')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_interviews', to='interview.question')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JumpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text Match'), ('range', 'Number Range')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_rules', to='interview.question')),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumps_to', to='interview.question')),
            ],
            options={
                'unique_together': {('from_question', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('rating', 'Rating')], max_length=20)),
                ('value', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.question')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('interview', 'question')},
            },
        ),
    ]
