# Generated by Django 5.2.15 on 2026-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview_created_at_interview_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumprule',
            name='condition_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text Match'), ('range', 'Number Range'), ('criteria_count', 'Criteria Count')], max_length=20),
        ),
    ]
