# Generated by Django 5.2.15 on 2026-06-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_code',
        ),
    ]
