# Generated by Django 5.2.15 on 2026-06-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patient_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='age',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='overview',
            name='alcohol_use',
            field=models.TextField(blank=True, help_text='How much have you been drinking?', verbose_name='Alcohol Use'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='alcohol_with_whom',
            field=models.TextField(blank=True, help_text='Who do you drink with?', verbose_name='Alcohol With Whom'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='attempt_past_week',
            field=models.BooleanField(default=False, help_text='Have you made any attempts in the past week?', verbose_name='Attempt Past Week'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='current_medications',
            field=models.TextField(blank=True, help_text='What medications are you taking?', verbose_name='Current Medications'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='drug_use',
            field=models.TextField(blank=True, help_text='Have you been using any drugs?', verbose_name='Drug Use'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='first_treatment_reason',
            field=models.TextField(blank=True, help_text='What was that for? What treatment(s) did you get?', verbose_name='First Treatment Reason'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='intention_details',
            field=models.TextField(blank=True, verbose_name='Intention Details'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='intention_past_week',
            field=models.BooleanField(default=False, help_text='Did you have any intention of attempting suicide in the past week?', verbose_name='Intention Past Week'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='most_severe_attempt',
            field=models.TextField(blank=True, help_text='Which attempt had the most severe consequences?', verbose_name='Most Severe Attempt'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='other_problems',
            field=models.TextField(blank=True, help_text='How are things going at work, at home, and with other people?', verbose_name='Other Problems'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='physical_health',
            field=models.TextField(blank=True, help_text='How has your physical health been?', verbose_name='Physical Health'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='plan_details',
            field=models.TextField(blank=True, help_text='Tell me about your plan.', verbose_name='Plan Details'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='plan_past_week',
            field=models.BooleanField(default=False, help_text='Have you thought about how you might do it?', verbose_name='Plan Past Week'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='presenting_problem',
            field=models.TextField(blank=True, help_text="What led to your coming here? What's the major problem?", verbose_name='Presenting Problem'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='strong_urge_details',
            field=models.TextField(blank=True, verbose_name='Strong Urge Details'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='strong_urge_past_week',
            field=models.BooleanField(default=False, help_text='Have you had a strong urge to kill yourself in the past week?', verbose_name='Strong Urge Past Week'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='suicide_attempt_details',
            field=models.TextField(blank=True, help_text='Tell me what happened.', verbose_name='Suicide Attempt Details'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='thoughts_past_week',
            field=models.BooleanField(default=False, help_text='Did you have any of these thoughts in the past week?', verbose_name='Thoughts Past Week'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='treatment_history',
            field=models.JSONField(blank=True, default=list, help_text='List of treatments', verbose_name='Treatment History'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='wished_dead',
            field=models.BooleanField(default=False, help_text='Have you ever wished you were dead?', verbose_name='Wished Dead'),
        ),
    ]
