# Generated by Django 5.2.15 on 2026-06-20 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_overview_age_remove_overview_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='alcohol_use',
            field=models.TextField(blank=True, help_text='در ماه گذشته، چقدر الکل مصرف کرده\u200cاید؟', verbose_name='چقدر الکل مصرف می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='alcohol_with_whom',
            field=models.TextField(blank=True, help_text='وقتی الکل مصرف می\u200cکنید، معمولاً با چه کسی هستید؟ (معمولاً تنها هستید یا با دیگران؟)', verbose_name='با چه کسی الکل مصرف می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='attempt_past_week',
            field=models.BooleanField(default=False, help_text='آیا در هفته گذشته (از جمله امروز) اقدام به خودکشی کرده\u200cاید؟', verbose_name='آیا در هفته گذشته اقدام به خودکشی کرده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overviews', to=settings.AUTH_USER_MODEL, verbose_name='مصاحبه\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='current_medications',
            field=models.TextField(blank=True, help_text='چه داروهایی، ویتامین\u200cها یا مکمل\u200cهای غذایی مصرف می\u200cکنید؟ (به جز آنهایی که قبلاً گفتید) با چه دوزی؟', verbose_name='چه داروهایی مصرف می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='disability_payments',
            field=models.BooleanField(default=False, help_text='آیا در حال حاضر مستمری دریافت می\u200cکنید؟', verbose_name='آیا مستمری دریافت می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='disability_reason',
            field=models.TextField(blank=True, help_text='به چه دلیلی مستمری دریافت می\u200cکنید؟', verbose_name='دلیل دریافت مستمری'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='drug_use',
            field=models.TextField(blank=True, help_text='در ماه گذشته، آیا مواد مخدر یا تفریحی مصرف کرده\u200cاید؟ آیا بیشتر از مقدار تجویز شده از داروهای خود استفاده کرده\u200cاید یا زودتر از موعد داروهایتان تمام شده است؟', verbose_name='آیا مواد مخدر مصرف می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='employment_status',
            field=models.CharField(blank=True, help_text='آیا در حال حاضر شاغل هستید؟ (درآمد دارید؟)', max_length=50, verbose_name='آیا در حال حاضر شاغل هستید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='first_treatment_age',
            field=models.CharField(blank=True, help_text='اولین بار چند ساله بودید که برای مشکلات عاطفی یا روانپزشکی به کسی مراجعه کردید؟', max_length=50, verbose_name='اولین بار چند ساله بودید که کمک گرفتید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='first_treatment_reason',
            field=models.TextField(blank=True, help_text='به خاطر چه مشکلی مراجعه کردید؟ چه درمانی دریافت کردید؟ چه داروهایی مصرف می\u200cکردید؟', verbose_name='چه مشکلی داشتید و چه درمانی دریافت کردید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='hospitalization_count',
            field=models.PositiveIntegerField(blank=True, help_text='چند بار در بیمارستان بستری شده\u200cاید؟', null=True, verbose_name='چند بار بستری شده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='hospitalization_reason',
            field=models.TextField(blank=True, help_text='به چه دلیل در بیمارستان بستری شدید؟', verbose_name='به چه دلیل بستری شدید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='intention_details',
            field=models.TextField(blank=True, help_text='در این مورد برایم توضیح دهید.', verbose_name='در این مورد توضیح دهید'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='intention_past_week',
            field=models.BooleanField(default=False, help_text='در هفته گذشته، آیا قصد داشته\u200cاید که اقدام به خودکشی کنید؟', verbose_name='آیا در هفته گذشته قصد خودکشی داشته\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='last_feeling_ok',
            field=models.CharField(blank=True, help_text='آخرین باری که احساس می\u200cکردید حالتان خوب است (حالت عادی خودتان) کی بود؟', max_length=100, verbose_name='آخرین باری که حال خوبی داشتید کی بود؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='living_place',
            field=models.CharField(blank=True, help_text='در چه نوع مکانی زندگی می\u200cکنید؟', max_length=200, verbose_name='در چه نوع مکانی زندگی می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='living_with',
            field=models.CharField(blank=True, help_text='با چه کسی زندگی می\u200cکنید؟', max_length=200, verbose_name='با چه کسی زندگی می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='medical_hospitalization',
            field=models.BooleanField(default=False, help_text='آیا تا به حال برای درمان یک مشکل پزشکی در بیمارستان بستری شده\u200cاید؟', verbose_name='آیا برای درمان مشکل پزشکی بستری شده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='medical_hospitalization_reason',
            field=models.TextField(blank=True, help_text='به چه دلیل در بیمارستان بستری شدید؟', verbose_name='به چه دلیل بستری شدید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='mood_description',
            field=models.TextField(blank=True, help_text='حالتان در ماه گذشته چگونه بوده است؟', verbose_name='حالتان چگونه بوده است؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='most_severe_attempt',
            field=models.TextField(blank=True, help_text='کدام اقدام شدیدترین عواقب پزشکی را داشت (رفتن به اورژانس، نیاز به بستری، نیاز به مراقبت در ICU)؟', verbose_name='شدیدترین اقدام کدام بود؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='occupation_history',
            field=models.CharField(blank=True, help_text='آیا همیشه همین شغل را داشته\u200cاید؟', max_length=200, verbose_name='آیا همیشه همین شغل را داشته\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='onset_circumstances',
            field=models.TextField(blank=True, help_text='چه اتفاقی در زندگی شما می\u200cگذشت که این مشکل شروع شد؟', verbose_name='چه اتفاقی در زندگی شما افتاده بود که این مشکل شروع شد؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='other_problems',
            field=models.TextField(blank=True, help_text='آیا در ماه گذشته مشکلات دیگری داشته\u200cاید؟ (اوضاع در کار، خانه و با دیگران چگونه است؟)', verbose_name='آیا مشکلات دیگری داشته\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='part_time_hours',
            field=models.PositiveIntegerField(blank=True, help_text='چند ساعت در هفته به صورت پاره\u200cوقت کار می\u200cکنید؟', null=True, verbose_name='چند ساعت در هفته کار می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='part_time_reason',
            field=models.TextField(blank=True, help_text='چرا به جای تمام\u200cوقت، پاره\u200cوقت کار می\u200cکنید؟', verbose_name='چرا پاره\u200cوقت کار می\u200cکنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='accounts.patient', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='physical_health',
            field=models.TextField(blank=True, help_text='سلامت جسمانی شما چگونه است؟ (آیا مشکل پزشکی خاصی دارید؟)', verbose_name='سلامت جسمانی شما چگونه است؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='plan_details',
            field=models.TextField(blank=True, help_text='به من بگویید به چه چیزی فکر می\u200cکردید. آیا به این فکر کرده\u200cاید که برای انجام این کار به چه چیزی نیاز دارید؟ آیا وسایل لازم را دارید؟', verbose_name='برنامه شما چیست؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='plan_past_week',
            field=models.BooleanField(default=False, help_text='در هفته گذشته، آیا به این فکر کرده\u200cاید که چطور ممکن است این کار را انجام دهید؟', verbose_name='آیا به این فکر کرده\u200cاید که چطور این کار را انجام دهید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='presenting_problem',
            field=models.TextField(blank=True, help_text='چه چیزی باعث شد اینجا بیایید؟ (مشکل اصلی شما چیست؟)', verbose_name='علت مراجعه شما چیست؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='psychiatric_hospitalization',
            field=models.BooleanField(default=False, help_text='آیا تا به حال در بیمارستان روانپزشکی بستری شده\u200cاید؟', verbose_name='آیا در بیمارستان روانپزشکی بستری شده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='self_harm',
            field=models.BooleanField(default=False, help_text='آیا تا به حال کاری کرده\u200cاید که به خودتان آسیب بزنید؟', verbose_name='آیا تا به حال به خودتان آسیب زده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='strong_urge_details',
            field=models.TextField(blank=True, help_text='در این مورد برایم توضیح دهید.', verbose_name='در این مورد توضیح دهید'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='strong_urge_past_week',
            field=models.BooleanField(default=False, help_text='آیا در هفته گذشته میل شدیدی برای کشتن خود داشته\u200cاید؟', verbose_name='آیا در هفته گذشته میل شدید به خودکشی داشته\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='substance_treatment',
            field=models.BooleanField(default=False, help_text='آیا تا به حال برای مصرف مواد مخدر یا الکل درمان شده\u200cاید؟', verbose_name='آیا برای مصرف مواد یا الکل درمان شده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='suicide_attempt',
            field=models.BooleanField(default=False, help_text='آیا تا به حال سعی کرده\u200cاید خودتان را بکشید؟', verbose_name='آیا تا به حال اقدام به خودکشی کرده\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='suicide_attempt_details',
            field=models.TextField(blank=True, help_text='چه کار کردید؟ (برایم بگویید چه اتفاقی افتاد.) آیا قصد پایان دادن به زندگی خود را داشتید؟', verbose_name='چه اتفاقی افتاد؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='thoughts_past_week',
            field=models.BooleanField(default=False, help_text='آیا در هفته گذشته (از جمله امروز) این افکار را داشته\u200cاید؟', verbose_name='آیا در هفته گذشته این افکار را داشته\u200cاید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='treatment_history',
            field=models.JSONField(blank=True, default=list, help_text='لیست درمان\u200cها: [{"age": "سن", "description": "توضیحات", "symptoms": "علائم", "triggering_events": "عوامل محرک", "treatment": "درمان", "offset": "نتیجه"}]', verbose_name='سابقه درمان\u200cها'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='unable_to_work_history',
            field=models.BooleanField(default=False, help_text='آیا تا به حال دوره\u200cای بوده که نتوانسته\u200cاید کار یا تحصیل کنید؟', verbose_name='آیا تا به حال نتوانسته\u200cاید کار یا تحصیل کنید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='unable_to_work_reason',
            field=models.TextField(blank=True, help_text='به چه دلیل نتوانسته\u200cاید کار یا تحصیل کنید؟', verbose_name='دلیل ناتوانی در کار یا تحصیل'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='unemployment_reason',
            field=models.TextField(blank=True, help_text='چرا بیکار هستید؟ آخرین بار کی کار می\u200cکردید؟ چگونه هزینه\u200cهای خود را تأمین می\u200cکنید؟', verbose_name='دلیل بیکاری'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='wished_dead',
            field=models.BooleanField(default=False, help_text='آیا تا به حال آرزو کرده\u200cاید که بمیرید یا کاش می\u200cخوابیدید و بیدار نمی\u200cشدید؟', verbose_name='آیا تا به حال آرزو کرده\u200cاید که بمیرید؟'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='wished_dead_details',
            field=models.TextField(blank=True, help_text='در این مورد برایم توضیح دهید.', verbose_name='در این مورد توضیح دهید'),
        ),
    ]
